#!/bin/sh
ifname="$1"     # Interface name
index="$2"      # Network index (PDN index)
apn="$3"        # Access point name
type="$4"       # ipv4 or ipv6

if [ "$type" = "ipv4" ] ; then

    ifaddr="$5" # Interface address
    addr1="$6"  # First IP address
    addr2="$7"  # Last IP address
    mask="$8"   # Mask

    #echo "*** Configuring IPv4 pdn '$apn' on ${ifname}, $ifaddr/$mask"

    # Configure interface
    ifconfig ${ifname} ${ifaddr}/${mask} up

    ipt=$(iptables -w 5 -S | grep "\-A INPUT \-i ${ifname} \-j ACCEPT")
    if [ "$ipt" = "" ] ; then
        iptables -w 5 -I INPUT -i ${ifname} -j ACCEPT
    fi

    # IPv6 is always enabled after ipv4
    echo '1' > /proc/sys/net/ipv6/conf/$ifname/disable_ipv6
else

    ll="$5"     # ipv6 link local address
    addr0="$6"  # Interface ipv6 address
    addr1="$7"  # first ipv6 prefix
    addr2="$8"  # last ipv6 prefix
    mask="$9"   # Mask

    #echo "*** Configuring IPv6 pdn '$apn' on ${ifname}, $addr0/$mask"

    echo '0' > /proc/sys/net/ipv6/conf/$ifname/disable_ipv6

    # Add link local address
    ifconfig ${ifname} inet6 add ${addr0}/${mask} up

    # Add route for all prefixes
    ip -6 route add ${addr1}/${mask} dev ${ifname}

    ipt=$(ip6tables -w 5 -S | grep "\-A INPUT \-i ${ifname} \-j ACCEPT")
    if [ "$ipt" = "" ] ; then
        ip6tables -w 5 -I INPUT -i ${ifname} -j ACCEPT
    fi
fi

